version: '3.8'

services:
  # Настройка Бэкенда
  backend:
    build: ./backend
    container_name: story_backend
    ports:
      - "8000:8000"
    volumes:
      # Важно: прокидываем папку data наружу, чтобы сохранения не стерлись при перезапуске!
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env  # Читаем токен бота

  # Настройка Фронтенда
  frontend:
    build: ./frontend
    container_name: story_frontend
    ports:
      - "80:80"
    depends_on:
      - backend # Фронт запустится только после Бэка